
app_reclamation_stats:
    path: /stats
    controller: App\Controller\ReclamationController::stats
    methods: ['GET']

app_reclamation_downloadPdfAll:
    path: '/download-pdf-all'
    controller: 'App\Controller\ReclamationController::downloadPdfAll'
    methods: ['GET']

    